{% set name = "dcm2niix" %}
{% set version = "1.0.20250506" %}
{% set sha256 = "1b24658678b6c24141e58760dbea9fe2786ffdd736bcc37a36d9cdabc731bafa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/rordenlab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - make
    - git
    - libtool  # [not win]
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}

test:
  commands:
    - dcm2niix -h

about:
  home: http://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage
  license: MIT
  license_file: license.txt
  summary: dcm2niix is a designed to convert neuroimaging data from the DICOM format to the NIfTI format.

  description: dcm2niix is a designed to convert neuroimaging data from the DICOM format to the NIfTI format.
  doc_url: https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii
  dev_url: https://github.com/rordenlab/dcm2niix

extra:
  recipe-maintainers:
    - kastman
    - ningfei
    - neurolabusc
    - hanayik
